server:
  port: 9820
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    username: root
    password: passw0rd
    driver: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #是否把自己注册到eureka服务器中
    fetch-registry: false   #是否从eureka服务器中获取注册信息
  server:
    my-url: http://${eureka.instance.hostname}:${server.port}/eureka/